import 'package:json_annotation/json_annotation.dart';
import 'package:agent_town_hall/core/base_entity.dart';
import 'package:agent_town_hall/patterns/embeddable.dart';
import 'observation_event_type.dart';

part 'observation_event.g.dart';

/// Agent-published observation in a room.
/// Immutable. Logged for semantic search and learning.
///
/// VALIDATION RULES:
/// - agentId: required UUID, must reference existing Agent
/// - roomId: required UUID, must reference existing Room
/// - turnNumber: required, >= 1
/// - eventType: required, must be valid enum
/// - content: required, length 1-5000 chars
/// - respondingToEventId: optional, if present must reference existing ObservationEvent in same room
/// - confidence: optional, if present must be 0.0-1.0 inclusive
/// - embedding: optional, auto-generated on save, read-only after creation
/// - timestamp: auto-set to UTC now() on creation, immutable
///
/// IMMUTABILITY:
/// - Once created, no fields can be modified
/// - Embedding is generated asynchronously after creation
/// - This entity is audit-safe: used to train agents and narratives
@JsonSerializable()
class ObservationEvent extends BaseEntity with Embeddable {
  /// Which agent published this observation
  /// Validation: required, must be valid UUID of Agent in this room
  final String agentId;

  /// Which room this observation belongs to
  /// Validation: required, must be valid UUID of Room
  final String roomId;

  /// Which turn this was published in
  /// Validation: required, >= 1
  final int turnNumber;

  /// Type of observation (enumerated for type safety)
  /// Validation: required, must be one of ObservationEventType values
  final ObservationEventType eventType;

  /// Human-readable content published by agent
  /// Validation: required, length 1-5000 characters
  final String content;

  /// Reference to parent event for threading
  /// Validation: optional, if present must reference valid ObservationEvent in same room
  final String? respondingToEventId;

  /// Agent's self-assessed confidence in this observation
  /// Validation: optional, if present must be 0.0-1.0 inclusive
  /// Semantics: 0.0 = complete guess, 1.0 = certain
  final double? confidence;

  /// Vector embedding for semantic search
  /// Validation: optional, auto-generated by EmbeddingService
  /// Generated: after event creation, stored back to event
  /// Dimensions: 768 (Jina default)
  final List<double>? embedding;

  /// When this observation was published (UTC)
  /// Validation: required, auto-set to DateTime.now().toUtc()
  /// Immutable: set once on creation, never changes
  final DateTime timestamp;

  /// Embeddable mixin implementation
  @override
  List<double>? get embeddingVector => embedding;

  @override
  String get embeddingText => content;

  ObservationEvent({
    required String id,
    required this.agentId,
    required this.roomId,
    required this.turnNumber,
    required this.eventType,
    required this.content,
    this.respondingToEventId,
    this.confidence,
    this.embedding,
    required this.timestamp,
  }) : super(id: id) {
    // Constructor validation (fail-fast)
    if (content.isEmpty || content.length > 5000) {
      throw ArgumentError('content must be 1-5000 chars');
    }
    if (confidence != null && (confidence! < 0.0 || confidence! > 1.0)) {
      throw ArgumentError('confidence must be 0.0-1.0');
    }
    if (turnNumber < 1) {
      throw ArgumentError('turnNumber must be >= 1');
    }
  }

  factory ObservationEvent.fromJson(Map<String, dynamic> json) =>
      _$ObservationEventFromJson(json);

  Map<String, dynamic> toJson() => _$ObservationEventToJson(this);
}
